### ISSUE TITLE
Screenplain doesn't filter ! at start of line to force action.

### ISSUE THREAD

**Issue by karlsaintlucy** [vilcans/screenplain#63]
Hiya, I use ! at the start of action lines to force them in my screenplays; would be great if Screenplain could filter those out.

**Comment by danielhjames** [comment]
I also experienced this issue when migrating from trelby to use fountain with screenplain.

In https://github.com/vilcans/screenplain/blob/master/screenplain/parsers/fountain.py lines 134-135 in append_dialog parse character names based on a leading @ symbol, but there is not yet an equivalent for exclamation marks in append_action on lines 173-177.

So it seems action lines get treated as default formatting and are output by the parser exactly as they appear in the input file, including a leading exclamation mark if present.

Personally, I like the aspect of fountain syntax where action lines have explicit markup, as it reduces the risk that an action line ends up part of some other element in the output because of user error with line breaks.

**Comment by danielhjames** [comment]
Awesome, thanks @vilcans !
